### ISSUE TITLE
Repository containing malicious content

### ISSUE THREAD

**Issue by flipp33r** [hawacodes/call-center-simulation#1]
Hi,
I hate to be a bearer of bad news, but it looks like this repository contains malware that you are likely not aware of.
Please treat this as a friendly notification. I suggest you to investigate origin of the below-mentioned file(s) and assume all systems involved in building or running your NetBeans project(s) to be fully compromised. I also suggest you review all your other repositories and NetBeans projects for presence of similar files.

Suspicious file(s):

- https://github.com/hawacodes/CallCenter/blob/master/CallCenter/nbproject/cache.dat - This is a malicious file intended to install additional malware on a system and/or modify NetBeans projects (see VirusTotal: https://www.virustotal.com/gui/file/a7d664bff764bfc2cc6b13c15b2d7d7f09d0e55f0c376a81b64644d85ebe1e0b/detection)
- https://github.com/hawacodes/CallCenter/blob/master/CallCenter/nbproject/build-impl.xml#L972 - This is a modified `build-impl.xml` file intended to run malicious JAR file `cache.dat` every time a project is build

Cheers,
Flipper

**Comment by hawacodes** [comment]
Dear Flipper,

Thank you so much for warning me about this situation. I deleted the files.

Best Regards,

Havva
